# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainControllerSoftware_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
import trainControllerSoftware_MainWindow
import trainControllerSoftware_TestSecondWindow
from trainControllerSoftware_MainWindow import Ui_TrainControllerSW_MainWindow
from trainControllerSoftware_TestSecondWindow import Ui_Test_SecondWindow

Ui_TrainControllerSW_MainWindow = dict()
Ui_Test_SecondWindow = dict()

