# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_window)
        self.verticalLayout.setObjectName("verticalLayout")

        ## "Toolbox" ##
        self.toolBox = QtWidgets.QToolBox(main_window)
        self.toolBox.setObjectName("toolBox")

        ######## Red Line ########
        self.redline_tab = QtWidgets.QWidget()
        self.redline_tab.setGeometry(QtCore.QRect(0, 0, 782, 520))
        self.redline_tab.setObjectName("redline_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.redline_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.redline_controllers = QtWidgets.QTabWidget(self.redline_tab)
        self.redline_controllers.setObjectName("redline_controllers")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")

        ## redline block occupancy table ##
        self.blockbox = QtWidgets.QGroupBox(self.tab)
        self.blockbox.setObjectName("blockbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.blockbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.block_table = QtWidgets.QTableWidget(self.blockbox)
        self.block_table.setObjectName("block_table")
        self.block_table.setColumnCount(3)
        self.block_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.block_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.block_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.block_table.setHorizontalHeaderItem(2, item)
        self.block_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.block_table.verticalHeader().hide()
        self.verticalLayout_4.addWidget(self.block_table)
        self.gridLayout.addWidget(self.blockbox, 0, 0, 1, 1)

        ## Switch Status table ##
        self.switch_block = QtWidgets.QGroupBox(self.tab)
        self.switch_block.setMinimumSize(QtCore.QSize(0, 180))
        self.switch_block.setObjectName("switch_block")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.switch_block)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.switch_table = QtWidgets.QTableWidget(self.switch_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch_table.sizePolicy().hasHeightForWidth())
        self.switch_table.setSizePolicy(sizePolicy)
        self.switch_table.setMinimumSize(QtCore.QSize(0, 40))
        self.switch_table.setObjectName("switch_table")
        self.switch_table.setColumnCount(3)
        self.switch_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.switch_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.switch_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.switch_table.setHorizontalHeaderItem(2, item)
        self.switch_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.switch_table.verticalHeader().hide()
        self.verticalLayout_8.addWidget(self.switch_table)
        self.gridLayout.addWidget(self.switch_block, 0, 1, 1, 1)

        ## Red line bottom half ##
        self.bottom_half = QtWidgets.QWidget(self.tab)
        self.bottom_half.setObjectName("bottom_half")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bottom_half)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        ## Fault table ##
        self.fault_box = QtWidgets.QGroupBox(self.bottom_half)
        self.fault_box.setMinimumSize(QtCore.QSize(0, 140))
        self.fault_box.setObjectName("fault_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fault_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fault_table = QtWidgets.QTableWidget(self.fault_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fault_table.sizePolicy().hasHeightForWidth())
        self.fault_table.setSizePolicy(sizePolicy)
        self.fault_table.setMinimumSize(QtCore.QSize(0, 60))
        self.fault_table.setObjectName("fault_table")
        self.fault_table.setColumnCount(4)
        self.fault_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fault_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fault_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fault_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fault_table.setHorizontalHeaderItem(3, item)
        self.fault_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalLayout_5.addWidget(self.fault_table)
        self.verticalLayout_3.addWidget(self.fault_box)

        ## Crossing status table ##
        self.crossing_box = QtWidgets.QGroupBox(self.bottom_half)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crossing_box.sizePolicy().hasHeightForWidth())
        self.crossing_box.setSizePolicy(sizePolicy)
        self.crossing_box.setMinimumSize(QtCore.QSize(0, 10))
        self.crossing_box.setObjectName("crossing_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.crossing_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.crossing_table = QtWidgets.QTableWidget(self.crossing_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crossing_table.sizePolicy().hasHeightForWidth())
        self.crossing_table.setSizePolicy(sizePolicy)
        self.crossing_table.setMinimumSize(QtCore.QSize(0, 40))
        self.crossing_table.setObjectName("crossing_table")
        self.crossing_table.setColumnCount(3)
        self.crossing_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.crossing_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.crossing_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.crossing_table.setHorizontalHeaderItem(2, item)
        self.crossing_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalLayout_6.addWidget(self.crossing_table)
        self.verticalLayout_3.addWidget(self.crossing_box)
        self.gridLayout.addWidget(self.bottom_half, 1, 0, 1, 2)

        ## Configure Button ##
        self.configure_button = QtWidgets.QToolButton(self.tab)
        self.configure_button.setMinimumSize(QtCore.QSize(10, 18))
        self.configure_button.setIconSize(QtCore.QSize(14, 14))
        self.configure_button.setObjectName("configure_button")
        self.gridLayout.addWidget(self.configure_button, 2, 0, 1, 1)
        self.redline_controllers.addTab(self.tab, "")

        ## Tab 2
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.redline_controllers.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.redline_controllers)
        self.toolBox.addItem(self.redline_tab, "")

        ######## Green Line ########
        self.greenline_tab = QtWidgets.QWidget()
        self.greenline_tab.setGeometry(QtCore.QRect(0, 0, 782, 520))
        self.greenline_tab.setObjectName("greenline_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.greenline_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.toolBox.addItem(self.greenline_tab, "")
        self.verticalLayout.addWidget(self.toolBox)

        self.retranslateUi(main_window)
        self.toolBox.setCurrentIndex(0)
        self.redline_controllers.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "main_window"))
        self.blockbox.setTitle(_translate("main_window", "Block Occupancy"))
        item = self.block_table.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "Block Number"))
        item = self.block_table.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Section"))
        item = self.block_table.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Block State"))
        self.switch_block.setTitle(_translate("main_window", "Switch States"))
        item = self.switch_table.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "Block Number"))
        item = self.switch_table.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Section"))
        item = self.switch_table.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Switch State"))
        self.fault_box.setTitle(_translate("main_window", "Faults"))
        item = self.fault_table.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "New Column"))
        item = self.fault_table.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Section"))
        item = self.fault_table.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Fault Id"))
        item = self.fault_table.horizontalHeaderItem(3)
        item.setText(_translate("main_window", "Fault Message"))
        self.crossing_box.setTitle(_translate("main_window", "Crossing State"))
        item = self.crossing_table.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "Block Number"))
        item = self.crossing_table.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Section"))
        item = self.crossing_table.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Crossing State"))
        self.configure_button.setText(_translate("main_window", "Configure Line"))
        self.redline_controllers.setTabText(self.redline_controllers.indexOf(self.tab), _translate("main_window", "Tab 1"))
        self.redline_controllers.setTabText(self.redline_controllers.indexOf(self.tab_2), _translate("main_window", "Tab 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.redline_tab), _translate("main_window", "Red Line"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.greenline_tab), _translate("main_window", "Green Line"))
