# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test-screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
sys.path.append('/home/garrett/git/ECE_1140_TRAINS/CTC-Office/block-functionality')
from PyQt5 import QtCore, QtGui, QtWidgets
from lines import redLine, redLineLookup

class Ui_testWindow(object):
    def setupUi(self, testWindow):
        testWindow.setObjectName("testWindow")
        testWindow.resize(400, 300)
        self.toggleOccupancy = QtWidgets.QPushButton(testWindow)
        self.toggleOccupancy.setGeometry(QtCore.QRect(50, 170, 131, 21))
        self.toggleOccupancy.setObjectName("toggleOccupancy")
        self.toggleFaultState = QtWidgets.QPushButton(testWindow)
        self.toggleFaultState.setGeometry(QtCore.QRect(50, 210, 131, 21))
        self.toggleFaultState.setObjectName("toggleFaultState")
        self.toggleFaultState.clicked.connect(self.toggleFaultStateButton)
        self.blockList = QtWidgets.QListWidget(testWindow)
        self.blockList.setGeometry(QtCore.QRect(220, 120, 131, 111))
        self.blockList.setMouseTracking(True)
        self.blockList.setSelectionRectVisible(True)
        self.blockList.setObjectName("blockList")
        item = QtWidgets.QListWidgetItem()
        self.blockList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.blockList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.blockList.addItem(item)

        self.retranslateUi(testWindow)
        QtCore.QMetaObject.connectSlotsByName(testWindow)

    def retranslateUi(self, testWindow):
        _translate = QtCore.QCoreApplication.translate
        testWindow.setWindowTitle(_translate("testWindow", "Form"))
        self.toggleOccupancy.setText(_translate("testWindow", "Toggle Occupancy"))
        self.toggleFaultState.setText(_translate("testWindow", "Toggle Fault State"))
        __sortingEnabled = self.blockList.isSortingEnabled()
        self.blockList.setSortingEnabled(False)
        item = self.blockList.item(0)
        item.setText(_translate("testWindow", "Block A"))
        item = self.blockList.item(1)
        item.setText(_translate("testWindow", "Block B"))
        item = self.blockList.item(2)
        item.setText(_translate("testWindow", "Block C"))
        self.blockList.setSortingEnabled(__sortingEnabled)

    def toggleFaultStateButton(self):
        selectedBlock = self.blockList.currentItem().text()
        blockIndex = redLineLookup[selectedBlock]
        redLine[blockIndex].toggleFaultState()

if __name__ == "__main__":
    import sys
    redLine[0].toggleFaultState()
    app = QtWidgets.QApplication(sys.argv)
    testWindow = QtWidgets.QWidget()
    ui = Ui_testWindow()
    ui.setupUi(testWindow)
    testWindow.show()
    sys.exit(app.exec_())
